rails_testing/bitlys/config/routes.rb
Rails.application.routes.draw do
  
  resources :urls
  root 'urls#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails_testing/bitlys/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_testing/bitlys/app/models/url.rb
class Url < ApplicationRecord
  validates :original, presence: true
  validates :original,  format: {with: /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix , message: "Url Format not valid"}  
  before_create :create_short_url

  def create_short_url
	self.short_url = "#{('a'..'z').to_a.shuffle[0,8].join}"
  end



end

rails_testing/bitlys/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails_testing/bitlys/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
	def index
  	@urls = Url.all.sort
  end

  def new 
  	@url = Url.new
  end

  def create 
		@url = Url.new(url_params)
   		if @url.save
   			redirect_to urls_path
   		else
   			render 'new'
   		end
  end

  def edit
 		@url = Url.find(params[:id])
    @url.click_count += 1
    @url.save
    redirect_to urls_path
	end

  private 
  	def url_params
  		params.require(:url).permit(:original)		
  	end 

end

rails_testing/bitlys/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_testing/bitlys/app/helpers/urls_helper.rb
module UrlsHelper
end

rails_testing/bitlys/app/views/urls/_form.html.erb
<h1>Bitly</h1>

<%= form_for @url do |f| %>
	<% if @url.errors.any? %>
		<div id="error explanation" %>
			<h2>
				<%= pluralize(@url.errors.count, "error") %>Han impedido que la Url se ha Grabada:
			</h2>
			<ul>
				<% @url.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<%end %>
	<p>
		<%= f.label :original %>
		<%= f.text_field :original %>
	</p>
	
	<p>
	<%= f.submit 'Create Url' %>
	</p>
<%end%> 

rails_testing/bitlys/app/views/urls/index.html.erb
<h1>Listado Urls</h1>

<%= link_to 'New Url', new_url_path %>
<table>
	<tr>
		<th>Url Original</th>
		<th>Short Url</th>
		<th>Counter</th>
	</tr>
	<% @urls.each do |url| %>
		<tr>
			<td><%=url.original %></td>
			<td><%=link_to "#{url.short_url}" edit_url_path(url) %></td>
			<td><%=url.click_count %></td>
		</tr>
	<% end %>
</table>

rails_testing/bitlys/app/views/urls/new.html.erb
<h1>New Url</h1>
<%= render 'form' %>
<%= link_to 'Back', urls_path %>