rails_testing/blog/config/routes.rb
Rails.application.routes.draw do
  
resources :articulos do
	resources :comentarios
end	
  root 'bienvenido#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails_testing/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_testing/blog/app/models/articulo.rb
class Articulo < ApplicationRecord
	has_many :comentarios
	validates :titular, presence: true, length: {minimum: 5}

end

rails_testing/blog/app/models/comentario.rb
class Comentario < ApplicationRecord
	belongs_to :articulo
end

rails_testing/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails_testing/blog/app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
	def index
		@articulos = Articulo.all
  end

	def show
		@articulo = Articulo.find(params[:id])
  end

	def new
  	@articulo = Articulo.new
  end 

  def edit
  	@articulo = Articulo.find(params[:id])
  end

	def create
		@articulo = Articulo.new(articulo_params)
		
		if @articulo.save
			redirect_to @articulo
		else
			render 'new'	
		end
	end

	def update
		@articulo = Articulo.find(params[:id])

		if @articulo.update(articulo_params)
			redirect_to @articulo
		else
			render 'edit'
		end

	end

	def destroy
		@articulo = Articulo.find(params[:id])
		@articulo.destroy

		redirect_to articulos_path
	end

	private
		def articulo_params
			params.require(:articulo).permit(:titular, :contenido)
		
		end

end

rails_testing/blog/app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

rails_testing/blog/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
	def create
		@articulo = Articulo.find(params[:articulo_id])
		@comentario = @articulo.comentarios.create(comentario_params)
		redirect_to articulo_path(@articulo)
	end

	def destroy
		@articulo = Articulo.find(params[:articulo_id])
		@comentario = @articulo.comentarios.find(params[:id])
		@comentario.destroy
		redirect_to articulo_path(@articulo)
	end

	private
		def comentario_params
			params.require(:comentario).permit(:comentarista,:contenido)
		end

end

rails_testing/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_testing/blog/app/helpers/articulos_helper.rb
module ArticulosHelper
end

rails_testing/blog/app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

rails_testing/blog/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

rails_testing/blog/app/helpers/index_helper.rb
module IndexHelper
end

rails_testing/blog/app/views/articulos/_form.html.erb
<%= form_for @articulo do |f| %>

	<% if @articulo.errors.any? %>
		<div id="error_explanation">
		<h2>
			<%= pluralize(@articulo.errors.count, "error") %> Han impedido que el articulo sea grabado:
		</h2>
			<ul>
				<% @articulo.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<%end%>

	<p>
		<%= f.label :titular %>
		<%= f.text_field :titular %>
	</p>

	<p>
		<%= f.label :contenido %>
		<%= f.text_area :contenido %>
	</p>

	<p>
		<%= f.submit 'Guardar Articulo' %>
	</p>
<% end %>

rails_testing/blog/app/views/articulos/edit.html.erb
<h1> Editar un articulo </h1>

<%= render 'form' %>
<%= link_to 'Volver', articulos_path %>

rails_testing/blog/app/views/articulos/index.html.erb
<h1> Listando Articulos </h1>

<%= link_to 'Nuevo Articulo', new_articulo_path%>
<table>
	<tr>
		<th>Titular</th>
		<th>Contenido</th>
		<th colspan="3"></th>
	</tr>

	<% @articulos.each do |articulo| %>
		<tr>
			<td><%=articulo.titular %></td>
			<td><%=articulo.contenido %></td>
			<td><%= link_to 'ver', articulo_path(articulo) %></td>
			<td><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
			<td><%= link_to 'Borrar', articulo_path(articulo), 
							method: :delete,
							data: {confirm: '¿Estas seguro?'} %></td>
		</tr>
	<% end %>
</table>

rails_testing/blog/app/views/articulos/new.html.erb
<h1>Nuevo Articulo</h1>
<%= render 'form' %>
<%= link_to 'volver', articulos_path %> 

rails_testing/blog/app/views/articulos/show.html.erb
<p>
	<strong>Titular:</strong>
	<%= @articulo.titular %>
</p>

<p>
	<strong>Contenido:</strong>
	<%= @articulo.contenido%>
</p>

<h2>Comentarios</h2>
<%= render @articulo.comentarios %>


<h2>Añadir un comentario: </h2>
<%= render 'comentarios/form' %>


<%= link_to 'volver', articulos_path %> 
<%= link_to 'Editar', edit_articulo_path(@articulo) %> 

rails_testing/blog/app/views/bienvenido/index.html.erb
<h1> Hola,rails</h1>
<%=link_to 'mi blog', controller: 'articulos' %>

rails_testing/blog/app/views/comentarios/_comentario.html.erb
<p> 
	<strong>Comentarista:</strong>
	<%= comentario.comentarista %>
</p>

<p>
<strong>Comentario:</strong>
	<%= comentario.contenido %>	
</p>

<p>
	<%= link_to 'Borrar Comentario', [comentario.articulo, comentario],
						method: :delete,
						data: {confirm: '¿Estas Seguro?'} %>
</p>

rails_testing/blog/app/views/comentarios/_form.html.erb
<%= form_for ([@articulo, @articulo.comentarios.build]) do |f| %>
	<p>
		<%= f.label :comentarista %><br>
		<%= f.text_field :comentarista %>
	</p>
	<p>
		<%= f.label :contenido %>
		<%= f.text_area :contenido %>
	</p>
	<p>
		<%= f.submit 'Guardar Comentario' %>
	</p>
<% end %>